### PR TITLE
Search Templates

### PR DESCRIPTION
**Pull request by garand**
Here is the current state of the search template. I personally prefer the content in a dropdown instead of broken up from the box.

image

Keep this open until we wrap up all of the front-end for search.

### CODE REVIEW

**Comment by matthewsimo** [comment]
Perhaps adding a "looking for results" state that loads when the start typing and then after they complete a few letters we can actually populate the results.. thoughts?

While this "makes sense" it might actually be poor UX/confusing/or juts "feel" slower, since for a lot of cases I bet it'd just flash up there real fast instead of just jumping directly loading in the results.. I realize this sentence doesn't make a lot of sense.

**Comment by garand** [comment]
@imbradmiller Take a look at this, I think it's looking good. What do you think?

**Comment by imbradmiller** [comment]
Where's the shapes, colors and fonts? It's the future. http://cl.ly/image/3m45281v3p0T

Looks good, lets roll with this.

**Comment by garand** [comment]
@matthewsimo You're right. I think search will work fast enough to render that pointless.

:+1: from everyone and I'll merge it in. :facepunch:

**Comment by matthewsimo** [comment]
:+1:

**Pull request merged**
