### PR TITLE
Need Validation Style for create issue module.

### PR DESCRIPTION
**Pull request by garand**

### CODE REVIEW

**Comment by garand** [comment]
@imbradmiller Let's transition this to a PR for all the form tweaks.

I've added support for an error class on form fields which will set their border color to a red.

image

Do you believe that this will be sufficient or would we also want to have a message outlining what caused the error?

@matthewsimo @chriswallace

**Comment by matthewsimo** [comment]
I'm a fan of info on "why things break", not just "hey! things are
broken".. Not sure what you're using for validation yet, or if you even
are.. But I think adding validation text is useful.

On Thu, Apr 25, 2013 at 4:38 PM, Anthony Garand notifications@github.comwrote:

> @imbradmiller https://github.com/imbradmiller Let's transition this to
> a PR for all the form tweaks.
> 
> I've added support for an error class on form fields which will set their
> border color to a red.
> 
> [image: image]https://f.cloud.github.com/assets/82437/427802/67eddeb2-adf0-11e2-8ce1-7d9c862af14e.png
> 
> Do you believe that this will be sufficient or would we also want to have
> a message outlining what caused the error?
> 
> @matthewsimo https://github.com/matthewsimo @chriswallacehttps://github.com/chriswallace
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LiftUX/IssuePress/pull/15#issuecomment-17042100
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
I agree. I think a simple message that states "Oops, these fields are required, Champ.".

**Comment by garand** [comment]
image

How's this work for you?

@matthewsimo I'm not currently doing actual js validation. I'm toying with parsley, but I havent implemented it yet.

If we're all good with this design, give me a :+1: and I'll integrate the style with parsley and we can merge it in.

**Comment by matthewsimo** [comment]
Fine with me, let's move forward..

On Fri, Apr 26, 2013 at 4:16 PM, Anthony Garand notifications@github.comwrote:

> [image: image]https://f.cloud.github.com/assets/82437/432978/10731a6e-aeb6-11e2-8613-f8e4c534ab7f.png
> 
> How's this work for you?
> 
> @matthewsimo https://github.com/matthewsimo I'm not currently doing
> actual js validation. I'm toying with parsley, but I havent implemented it
> yet.
> 
> If we're all good with this design, give me a [image: :+1:] and I'll
> integrate the style with parsley and we can merge it in.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LiftUX/IssuePress/pull/15#issuecomment-17100451
> .

## 
- Matthew Simo

**Comment by imbradmiller** [comment]
I'm ok with this. Lets move forward.

**Comment by garand** [comment]
Added parsley validation.

**Pull request closed without merging**
