### PR TITLE
Support Section Template

### PR DESCRIPTION
**Pull request by garand**
We need to see this styled. A mixture of data for a specific support section.
Screen Shot 2013-04-22 at 2 47 31 PM

### CODE REVIEW

**Comment by garand** [comment]
@imbradmiller Can you confirm the message above?

**Comment by imbradmiller** [comment]
Affirmative. Please proceed with pursuit of suspect. Copy, Front End Eagle.

**Comment by garand** [comment]
Also @imbradmiller, is this module different than this one?

image

**Comment by garand** [comment]
image

What do you think guys?

@matthewsimo @imbradmiller

**Comment by imbradmiller** [comment]
@garand, looks good and yes the module is a different module. :)

**Comment by matthewsimo** [comment]
I think that most of the time the issue title, won't reference the repo it exists within, if this module is in a 'global' context, it would definitely need some data on where each item "lives". If that doesn't makes sense, lmk.

I think just changing the text to "[user] [action] in [location]" on the line above the title would suffice.. thoughts?

**Comment by garand** [comment]
I'm down with that @matthewsimo.  How would you reference the [location] for comments?

**Comment by matthewsimo** [comment]
Comments are still tied to issues, which have a parent repo. It's just a matter of referencing the issue's repo.. or am I missing something?

**Comment by garand** [comment]
I'm referring to the screenshot above, where it says "imbradmiller said". I like your idea of changing the bottom ones to "imbradmiller open an issue on garageband", but I'd like your thoughts on how to put the repo name in the "imbradmiller said" message.

**Comment by matthewsimo** [comment]
I'd think "imbradmiller commented on an issue in garageband" would work. I also think that the issue should linke off to the issue and the reponame should link off to the repo.. just my thoughts though..

**Comment by garand** [comment]
Yea, agreed. I'll make those changes and add some a tags in.

**Comment by garand** [comment]
image

What do you guys think? Ready to merge?

**Comment by garand** [comment]
@imbradmiller @matthewsimo Does this look good to you?

**Comment by imbradmiller** [comment]
I see nothing wrong with this. @matthewsimo or @chriswallace, let me know if you have any objections. :)

**Comment by matthewsimo** [comment]
:+1:

On Tue, Apr 30, 2013 at 8:56 AM, Brad Miller notifications@github.comwrote:

> I see nothing wrong with this. @matthewsimohttps://github.com/matthewsimoor
> @chriswallace https://github.com/chriswallace, let me know if you have
> any objections. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LiftUX/IssuePress/pull/18#issuecomment-17228477
> .

## 
- Matthew Simo

**Pull request merged**
